### ISSUE TITLE
FuseBox 2.0

### ISSUE THREAD

**Issue by nchanged** [ArekusuNaito/electron-fuse-box-babel-live-reload-boilerplate#2]
Could you consider updating the seed to fusebox 2.0?
That's typescript version 

https://github.com/fuse-box/fuse-box-electron-seed.git

Thanks ;-)

**Comment by ArekusuNaito** [comment]
I'm back to have a bit more free-time. I'm deeply sorry for the laaaate response.
Do you guys still need something?
